name: Delete npm Package Version
on:
  workflow_dispatch:
jobs:
  delete-package:
    runs-on: ubuntu-latest
    steps:
      
      # - name: Delete package version
      #   uses: actions/delete-package-versions@v5
      #   with:
      #     package-name: 'your-package-name'
      #     package-type: 'npm'
      #     # num-old-versions-to-delete: #   do not use, dangerous
      #     token: ${{ secrets.GITHUB_TOKEN }}

