name: General Library CI/CD Workflow
# Shared by multiple projects

on:
  workflow_call:
    inputs:
      debug_mode:
        required: false
        type: boolean
        default: false # DEBUG MODE ENABLED
    secrets:
      pat_token:
        required: false

jobs:
  pull-request-event:
    runs-on: ubuntu-latest
    if:  github.event_name == 'pull_request' || github.event_name == 'pull_request_target' || inputs.debug_mode
    permissions:
      contents: read
      packages: write
    steps:
      - name: Echo Step
        run: |
          echo "Processing ${{ github.event_name }} event"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "repository: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "ref: ${{ github.event.pull_request.head.ref }}"

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run lint and unit tests
        uses: tetherto/qvac-devops/.github/actions/run-lint-and-unit-tests@production-workflows-tag
        with:
          gpr-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}

      - name: Run integration tests if labeled
        if: contains(github.event.pull_request.labels.*.name, 'verify')
        uses: tetherto/qvac-devops/.github/actions/run-lint-and-integration-tests@production-workflows-tag
        with:
          gpr-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}

      - name: Check for disallowed dependencies
        run: |
          deps=$(jq -r '[.dependencies // {}, .devDependencies // {}] | add | to_entries[] | .value' package.json)
          if echo "$deps" | grep -Eq '^(git\+https:\/\/github.com|[0-9]+\.[0-9]+\.[0-9]+-(dev|tmp)[^"]*)$'; then
            echo "::error title=Disallowed dependency detected::Do not use git URLs or dev/tmp versions in dependencies"
            exit 1
          fi

      - name: Check for @qvac/ prefix in package name
        run: |
          if ! grep -q '"name": "@qvac/' package.json; then
            echo "::error title=Invalid package name::Package name in package.json must start with @qvac/"
            exit 1
          fi

      - name: Call Publish NPM Action
        if: ${{ github.event.pull_request.head.repo.full_name != 'tetherto/qvac-devops' }}
        uses: tetherto/qvac-devops/.github/actions/publish-library-to-npm@production-workflows-tag
        with:
          secret-token: ${{ secrets.NPM_TOKEN }}
          tag: "dev"

  push-event:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || inputs.debug_mode
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish to NPM
        if: ${{ github.event.pull_request.head.repo.full_name != 'tetherto/qvac-devops' }}
        uses: tetherto/qvac-devops/.github/actions/publish-library-to-npm@production-workflows-tag
        with:
          secret-token: ${{ secrets.NPM_TOKEN }}

  debug-print:
    uses: ./.github/workflows/debugger-reusable.yml
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
